silent! colorscheme lucid
set t_Co=256

set showcmd
filetype plugin on
set number relativenumber
augroup numbertoggle
    autocmd!
    " https://gist.github.com/nobe4/aa8313fe98ca8821afad
    autocmd WinEnter,BufEnter,FocusGained,InsertLeave * set relativenumber
    autocmd WinLeave,BufLeave,FocusLost,InsertEnter * set norelativenumber
augroup END

" Turn on cursor line
set cursorline

" Set chars for whitespace
set listchars=tab:»\ ,trail:•,nbsp:•
set list


"https://stackoverflow.com/questions/29167604/setting-vim-cursorline-colors
"hi Cursor ctermfg=White ctermbg=Yellow cterm=bold guifg=white guibg=yellow
"hi gui=bold

"hi CursorColumn ctermfg=White ctermbg=Yellow cterm=bold guifg=white
"hi guibg=yellow gui=bold


" Splits below and to the right
set splitbelow
set splitright

" Search options
set ignorecase
set smartcase
" Map <esc> to quickly turn off highlight of last search
" WARNING: Causes error which presses c immediately upon opening vim.
" nnoremap <silent> <esc> :nohlsearch<CR><esc>

" Change the tabbing for python
function SetPythonOptions()
    echo "Called SetPythonOptions"
endfunction

setlocal tabstop=4
set softtabstop=4
set shiftwidth=4
set textwidth=79
set expandtab
set autoindent



autocmd FileType python call SetPythonOptions()


" Change tabbing for makefile
function SetMakeOptions()
    echo "Called SetMakeOptions"
    setlocal noexpandtab
endfunction

autocmd FileType make call SetMakeOptions()

" HTML
function SetHtmlOptions()
    echo "Called SetHtmlOptions"
    set softtabstop=2
    set tabstop=2
    set shiftwidth=2
endfunction

" au BufNewFile,BufRead,FileType *.js, *.html, *.css
"    \ set tabstop=2
"    \ set softtabstop=2
"    \ set shiftwidth=2

autocmd FileType html call SetHtmlOptions()
autocmd FileType javascript call SetHtmlOptions()


" Turn off arrow keys to force use of hjkl
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Remaps for switching vim panes
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

" Remaps for setting up snippets
nnoremap ,html :-1read $HOME/.vim/snippets/skeleton.html<CR>3jf>a


